Data migration
adobe/aepsdk-userprofile-ios pull request #22
Opened 2020-11-09 16:33 UTC by yangyansong-adbe

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-11-30 18:27 UTC, shalehaha requested changes

2020-11-30 18:27 UTC, shalehaha commented on AEPUserProfile/Sources/UserProfile.swift
> +public enum UserProfileV5Migrator {
shouldn't be public

2020-11-30 18:27 UTC, shalehaha commented on AEPUserProfile/Sources/UserProfile.swift
> +        guard let json = UserDefaults.standard.object(forKey: UserProfileConstants.V5Migration.USER_PROFILE_KEY) as? String, let jsonData = json.data(using: .utf8) else {
it'd better to first check if `UserProfileConstants.V5Migration.USER_PROFILE_KEY` exists, if not, print a trace log saying not data to migrate.

2020-11-30 18:27 UTC, shalehaha commented on AEPUserProfile/Sources/UserProfile.swift
> +            Log.trace(label: UserProfile.LOG_TAG, "Start to do data migration")
"Start data migration"

2020-11-30 18:27 UTC, shalehaha commented on AEPUserProfile/Sources/UserProfile.swift
> +public enum UserProfileV5Migrator {
also I'd move it to a sperate class

2020-12-02 17:48 UTC, yangyansong-adbe commented
@shalehaha  Review comments have been addressed.

2020-12-02 18:45 UTC, shalehaha approved these changes

2020-12-02 18:45 UTC, merged